# Generated by Django 5.2.14 on 2026-06-10 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_cniregion_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='sectors/%Y/%m/')),
                ('color_hex', models.CharField(blank=True, default='', max_length=7)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=275, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimated_jobs', models.PositiveIntegerField(blank=True, null=True)),
                ('project_stage', models.CharField(choices=[('idea', 'Idea'), ('planning', 'Planificación'), ('execution', 'Ejecución'), ('operating', 'En operación'), ('completed', 'Completado')], db_index=True, default='idea', max_length=16)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='geo.department')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='geo.municipality')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='geo.cniregion')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='investment.sector')),
            ],
            options={
                'verbose_name': 'Proyecto de inversión',
                'verbose_name_plural': 'Proyectos de inversión',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=275, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimated_jobs', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En progreso'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=16)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='geo.department')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='geo.cniregion')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='investment.sector')),
            ],
            options={
                'verbose_name': 'Oportunidad de inversión',
                'verbose_name_plural': 'Oportunidades de inversión',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=275, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.FileField(blank=True, null=True, upload_to='success_stories/%Y/%m/')),
                ('country_origin', models.CharField(blank=True, default='', max_length=120)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('jobs_generated', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='investment.sector')),
            ],
            options={
                'verbose_name': 'Caso de éxito',
                'verbose_name_plural': 'Casos de éxito',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
