# Generated by Django 5.2.14 on 2026-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='project_stage',
            field=models.CharField(choices=[('promotion', 'Promoción'), ('announced', 'Anunciado'), ('startup', 'Arranque'), ('implementing', 'Implementando'), ('stalled', 'Parado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='promotion', max_length=16),
        ),
    ]
