# Generated by Django 5.2.16 on 2026-07-31 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_investmentproject_project_stage'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ('order', '-published_at', '-created_at', '-id'), 'verbose_name': 'Caso de éxito', 'verbose_name_plural': 'Casos de éxito'},
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='is_public',
        ),
        migrations.AddField(
            model_name='sector',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='short_description_es',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successstory',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_story_logos', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='successstory',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='successstory',
            name='summary_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='summary_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='testimonial_author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='successstory',
            name='testimonial_author_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='testimonial_author_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='testimonial_quote',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='successstory',
            name='testimonial_quote_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='testimonial_quote_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
