# Generated by Django 5.2.17 on 2026-08-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_successstory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ('order', '-is_featured', '-published_at', '-created_at', '-id'), 'verbose_name': 'Caso de éxito', 'verbose_name_plural': 'Casos de éxito'},
        ),
    ]
