# Generated by Django 5.2.16 on 2026-10-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_investmentopportunity_location'),
        ('media_library', '0002_mediaasset_file_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunity',
            name='amount_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='amount_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='extra_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='investment_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='location_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='phase_detail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='amount_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='amount_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='extra_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='investment_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='location_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='phase_detail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
