# Generated by Django 5.2.17 on 2026-08-04 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='seo_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='seo_description_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='seo_title_es',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'xlsx', 'pptx', 'zip'])]),
        ),
    ]
