# Generated by Django 5.2.14 on 2026-06-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('country', models.CharField(blank=True, default='', max_length=120, verbose_name='País')),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('in_review', 'En revisión'), ('contacted', 'Contactado'), ('closed', 'Cerrado'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='Estado')),
                ('crm_synced', models.BooleanField(db_index=True, default=False, verbose_name='Sincronizado con CRM')),
                ('crm_record_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID en CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensaje')),
                ('advisory_type', models.CharField(blank=True, default='', max_length=150, verbose_name='Tipo de asesoría')),
                ('sector', models.CharField(blank=True, default='', max_length=150, verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Solicitud de asesoría',
                'verbose_name_plural': 'Solicitudes de asesoría',
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('country', models.CharField(blank=True, default='', max_length=120, verbose_name='País')),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('in_review', 'En revisión'), ('contacted', 'Contactado'), ('closed', 'Cerrado'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='Estado')),
                ('crm_synced', models.BooleanField(db_index=True, default=False, verbose_name='Sincronizado con CRM')),
                ('crm_record_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID en CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('country', models.CharField(blank=True, default='', max_length=120, verbose_name='País')),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('in_review', 'En revisión'), ('contacted', 'Contactado'), ('closed', 'Cerrado'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='Estado')),
                ('crm_synced', models.BooleanField(db_index=True, default=False, verbose_name='Sincronizado con CRM')),
                ('crm_record_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID en CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True, default='', verbose_name='Detalles del proyecto')),
                ('sector', models.CharField(blank=True, default='', max_length=150, verbose_name='Sector')),
                ('department', models.CharField(blank=True, default='', max_length=150, verbose_name='Departamento')),
                ('estimated_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Inversión estimada')),
            ],
            options={
                'verbose_name': 'Postulación de proyecto',
                'verbose_name_plural': 'Postulaciones de proyectos',
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceDownloadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('country', models.CharField(blank=True, default='', max_length=120, verbose_name='País')),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('in_review', 'En revisión'), ('contacted', 'Contactado'), ('closed', 'Cerrado'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='Estado')),
                ('crm_synced', models.BooleanField(db_index=True, default=False, verbose_name='Sincronizado con CRM')),
                ('crm_record_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID en CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Recurso solicitado')),
                ('details', models.TextField(blank=True, default='', verbose_name='Detalles')),
            ],
            options={
                'verbose_name': 'Lead de descarga de recurso',
                'verbose_name_plural': 'Leads de descarga de recursos',
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
    ]
