# Generated by Django 5.2.14 on 2026-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento de contacto'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='expected_jobs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Empleos esperados'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='investment_range',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Rango de inversión'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje adicional'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='project_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ubicación del proyecto'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del proyecto'),
        ),
    ]
