# Generated by Django 5.2.16 on 2026-07-31 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_institutionallink_alter_document_options_and_more'),
        ('forms_app', '0002_projectapplication_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedownloadlead',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_leads', to='cms.document', verbose_name='Documento'),
        ),
    ]
