#!/usr/bin/env bash
# Generate SIGI CNI custom fields, dropdown lists and labels via SuiteCRM custom/Extension.
# Does not modify core files or write to the database.
# Run from anywhere: bash crm/scripts/apply-sigi-cni-suitecrm-customizations.sh
# Or from crm/: bash scripts/apply-sigi-cni-suitecrm-customizations.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRM_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
LEGACY_DIR="${CRM_DIR}/suitecrm/public/legacy"

if [[ ! -d "${LEGACY_DIR}" ]]; then
  echo "Error: SuiteCRM legacy path not found:"
  echo "  ${LEGACY_DIR}"
  echo ""
  echo "Install SuiteCRM locally under crm/suitecrm/ first."
  echo "Expected layout: crm/suitecrm/public/legacy/"
  exit 1
fi

EXT_BASE="${LEGACY_DIR}/custom/Extension"

DIRS=(
  "${EXT_BASE}/application/Ext/Language"
  "${EXT_BASE}/modules/Accounts/Ext/Vardefs"
  "${EXT_BASE}/modules/Accounts/Ext/Language"
  "${EXT_BASE}/modules/Contacts/Ext/Vardefs"
  "${EXT_BASE}/modules/Contacts/Ext/Language"
  "${EXT_BASE}/modules/Opportunities/Ext/Vardefs"
  "${EXT_BASE}/modules/Opportunities/Ext/Language"
  "${EXT_BASE}/modules/Leads/Ext/Vardefs"
  "${EXT_BASE}/modules/Leads/Ext/Language"
)

for dir in "${DIRS[@]}"; do
  mkdir -p "${dir}"
done

write_file() {
  local dest="$1"
  shift
  cat > "${dest}"
  echo "[OK] ${dest#${CRM_DIR}/}"
}

# Writes identical label/list content for es_es and en_us (institutional CNI Spanish labels).
write_lang_files() {
  local dir="$1"
  local suffix="$2"
  local header="$3"
  shift 3
  local php_body
  php_body="$(cat)"
  local locale
  for locale in es_es en_us; do
    write_file "${dir}/${locale}.${suffix}.php" <<PHP
<?php
// SIGI CNI — ${header} (${locale}; generated by apply-sigi-cni-suitecrm-customizations.sh)

${php_body}
PHP
  done
}

write_lang_files "${EXT_BASE}/application/Ext/Language" "sigi_cni_lists" "global dropdown lists" <<'PHP'
$app_list_strings['estado_ciclo_vida_list'] = array(
    'conexion' => 'Conexión',
    'aliado' => 'Aliado',
    'lead' => 'Lead',
    'lead_calificado' => 'Lead Calificado',
    'promotor' => 'Promotor',
    'prospecto' => 'Prospecto',
    'oportunidad' => 'Oportunidad',
    'inversionista' => 'Inversionista',
    'empresa_operacional' => 'Empresa Operacional',
);

$app_list_strings['sector_economico_cni_list'] = array(
    'agroindustria' => 'Agroindustria',
    'turismo' => 'Turismo',
    'energia' => 'Energía',
    'manufactura' => 'Manufactura',
    'infraestructura' => 'Infraestructura',
    'otro' => 'Otro',
);

$app_list_strings['fuente_contacto_cni_list'] = array(
    'website' => 'Sitio web',
    'evento' => 'Evento',
    'referido' => 'Referido',
    'campana' => 'Campaña',
    'contacto_directo' => 'Contacto directo',
    'otro' => 'Otro',
);

$app_list_strings['prioridad_cni_list'] = array(
    'alta' => 'Alta',
    'media' => 'Media',
    'baja' => 'Baja',
);

$app_list_strings['tipo_inversion_cni_list'] = array(
    'greenfield' => 'Greenfield',
    'expansion' => 'Expansión',
    'merger_acquisition' => 'Fusión / adquisición',
    'joint_venture' => 'Joint venture',
    'otro' => 'Otro',
);

$app_list_strings['estado_proyecto_cni_list'] = array(
    'promotion' => 'Promoción',
    'announced' => 'Anunciado',
    'startup' => 'Arranque',
    'implementing' => 'Implementando',
    'stalled' => 'Parado',
    'finished' => 'Finalizado',
    'cancelled' => 'Cancelado',
);

$app_list_strings['idioma_preferido_cni_list'] = array(
    'es' => 'Español',
    'en' => 'Inglés',
);

$app_list_strings['estado_lead_cni_list'] = array(
    'por_contactar' => 'Por contactar',
    'intento_conectar' => 'Intento de conectar',
    'interesado' => 'Interesado',
    'no_interesado' => 'No interesado',
    'inactivo' => 'Inactivo',
);
PHP

write_file "${EXT_BASE}/modules/Accounts/Ext/Vardefs/sigi_cni_fields.php" <<'PHP'
<?php
// SIGI CNI — Accounts custom fields (generated by apply-sigi-cni-suitecrm-customizations.sh)

$dictionary['Account']['fields']['tipo_entidad_c'] = array(
    'name' => 'tipo_entidad_c',
    'vname' => 'LBL_TIPO_ENTIDAD',
    'type' => 'varchar',
    'len' => '100',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['pais_origen_c'] = array(
    'name' => 'pais_origen_c',
    'vname' => 'LBL_PAIS_ORIGEN',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['sector_economico_c'] = array(
    'name' => 'sector_economico_c',
    'vname' => 'LBL_SECTOR_ECONOMICO',
    'type' => 'enum',
    'options' => 'sector_economico_cni_list',
    'len' => '100',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['cliente_objetivo_c'] = array(
    'name' => 'cliente_objetivo_c',
    'vname' => 'LBL_CLIENTE_OBJETIVO',
    'type' => 'bool',
    'default' => '0',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['estado_ciclo_vida_c'] = array(
    'name' => 'estado_ciclo_vida_c',
    'vname' => 'LBL_ESTADO_CICLO_VIDA',
    'type' => 'enum',
    'options' => 'estado_ciclo_vida_list',
    'len' => '100',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['fuente_contacto_c'] = array(
    'name' => 'fuente_contacto_c',
    'vname' => 'LBL_FUENTE_CONTACTO',
    'type' => 'enum',
    'options' => 'fuente_contacto_cni_list',
    'len' => '100',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['monto_potencial_c'] = array(
    'name' => 'monto_potencial_c',
    'vname' => 'LBL_MONTO_POTENCIAL',
    'type' => 'currency',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['empleos_potenciales_c'] = array(
    'name' => 'empleos_potenciales_c',
    'vname' => 'LBL_EMPLEOS_POTENCIALES',
    'type' => 'int',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['fecha_primer_contacto_c'] = array(
    'name' => 'fecha_primer_contacto_c',
    'vname' => 'LBL_FECHA_PRIMER_CONTACTO',
    'type' => 'date',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Account']['fields']['ultima_interaccion_c'] = array(
    'name' => 'ultima_interaccion_c',
    'vname' => 'LBL_ULTIMA_INTERACCION',
    'type' => 'datetime',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);
PHP

write_lang_files "${EXT_BASE}/modules/Accounts/Ext/Language" "sigi_cni_fields" "Accounts field labels" <<'PHP'
$mod_strings['LBL_TIPO_ENTIDAD'] = 'Tipo de entidad';
$mod_strings['LBL_PAIS_ORIGEN'] = 'País de origen';
$mod_strings['LBL_SECTOR_ECONOMICO'] = 'Sector económico';
$mod_strings['LBL_CLIENTE_OBJETIVO'] = 'Cliente objetivo';
$mod_strings['LBL_ESTADO_CICLO_VIDA'] = 'Estado ciclo de vida';
$mod_strings['LBL_FUENTE_CONTACTO'] = 'Fuente de contacto';
$mod_strings['LBL_MONTO_POTENCIAL'] = 'Monto potencial';
$mod_strings['LBL_EMPLEOS_POTENCIALES'] = 'Empleos potenciales';
$mod_strings['LBL_FECHA_PRIMER_CONTACTO'] = 'Fecha primer contacto';
$mod_strings['LBL_ULTIMA_INTERACCION'] = 'Última interacción';
PHP

write_file "${EXT_BASE}/modules/Contacts/Ext/Vardefs/sigi_cni_fields.php" <<'PHP'
<?php
// SIGI CNI — Contacts custom fields (generated by apply-sigi-cni-suitecrm-customizations.sh)

$dictionary['Contact']['fields']['estado_lead_c'] = array(
    'name' => 'estado_lead_c',
    'vname' => 'LBL_ESTADO_LEAD',
    'type' => 'enum',
    'options' => 'estado_lead_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Contact']['fields']['idioma_preferido_c'] = array(
    'name' => 'idioma_preferido_c',
    'vname' => 'LBL_IDIOMA_PREFERIDO',
    'type' => 'enum',
    'options' => 'idioma_preferido_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Contact']['fields']['sector_interes_c'] = array(
    'name' => 'sector_interes_c',
    'vname' => 'LBL_SECTOR_INTERES',
    'type' => 'enum',
    'options' => 'sector_economico_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Contact']['fields']['fuente_entrada_c'] = array(
    'name' => 'fuente_entrada_c',
    'vname' => 'LBL_FUENTE_ENTRADA',
    'type' => 'enum',
    'options' => 'fuente_contacto_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Contact']['fields']['consentimiento_comunicaciones_c'] = array(
    'name' => 'consentimiento_comunicaciones_c',
    'vname' => 'LBL_CONSENTIMIENTO_COMUNICACIONES',
    'type' => 'bool',
    'default' => '0',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Contact']['fields']['cargo_institucional_c'] = array(
    'name' => 'cargo_institucional_c',
    'vname' => 'LBL_CARGO_INSTITUCIONAL',
    'type' => 'varchar',
    'len' => '150',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Contact']['fields']['pais_contacto_c'] = array(
    'name' => 'pais_contacto_c',
    'vname' => 'LBL_PAIS_CONTACTO',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);
PHP

write_lang_files "${EXT_BASE}/modules/Contacts/Ext/Language" "sigi_cni_fields" "Contacts field labels" <<'PHP'
$mod_strings['LBL_ESTADO_LEAD'] = 'Estado del lead';
$mod_strings['LBL_IDIOMA_PREFERIDO'] = 'Idioma preferido';
$mod_strings['LBL_SECTOR_INTERES'] = 'Sector de interés';
$mod_strings['LBL_FUENTE_ENTRADA'] = 'Fuente de entrada';
$mod_strings['LBL_CONSENTIMIENTO_COMUNICACIONES'] = 'Consentimiento comunicaciones';
$mod_strings['LBL_CARGO_INSTITUCIONAL'] = 'Cargo institucional';
$mod_strings['LBL_PAIS_CONTACTO'] = 'País del contacto';
PHP

write_file "${EXT_BASE}/modules/Opportunities/Ext/Vardefs/sigi_cni_fields.php" <<'PHP'
<?php
// SIGI CNI — Opportunities custom fields (generated by apply-sigi-cni-suitecrm-customizations.sh)

$dictionary['Opportunity']['fields']['sector_c'] = array(
    'name' => 'sector_c',
    'vname' => 'LBL_SECTOR',
    'type' => 'enum',
    'options' => 'sector_economico_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['monto_inversion_c'] = array(
    'name' => 'monto_inversion_c',
    'vname' => 'LBL_MONTO_INVERSION',
    'type' => 'currency',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['empleos_estimados_c'] = array(
    'name' => 'empleos_estimados_c',
    'vname' => 'LBL_EMPLEOS_ESTIMADOS',
    'type' => 'int',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['departamento_c'] = array(
    'name' => 'departamento_c',
    'vname' => 'LBL_DEPARTAMENTO',
    'type' => 'varchar',
    'len' => '150',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['municipio_c'] = array(
    'name' => 'municipio_c',
    'vname' => 'LBL_MUNICIPIO',
    'type' => 'varchar',
    'len' => '150',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['fecha_anuncio_c'] = array(
    'name' => 'fecha_anuncio_c',
    'vname' => 'LBL_FECHA_ANUNCIO',
    'type' => 'date',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['fecha_inicio_estimada_c'] = array(
    'name' => 'fecha_inicio_estimada_c',
    'vname' => 'LBL_FECHA_INICIO_ESTIMADA',
    'type' => 'date',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['fecha_finalizacion_estimada_c'] = array(
    'name' => 'fecha_finalizacion_estimada_c',
    'vname' => 'LBL_FECHA_FINALIZACION_ESTIMADA',
    'type' => 'date',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['obstaculos_identificados_c'] = array(
    'name' => 'obstaculos_identificados_c',
    'vname' => 'LBL_OBSTACULOS_IDENTIFICADOS',
    'type' => 'text',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['instituciones_involucradas_c'] = array(
    'name' => 'instituciones_involucradas_c',
    'vname' => 'LBL_INSTITUCIONES_INVOLUCRADAS',
    'type' => 'text',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['prioridad_c'] = array(
    'name' => 'prioridad_c',
    'vname' => 'LBL_PRIORIDAD',
    'type' => 'enum',
    'options' => 'prioridad_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['tipo_inversion_c'] = array(
    'name' => 'tipo_inversion_c',
    'vname' => 'LBL_TIPO_INVERSION',
    'type' => 'enum',
    'options' => 'tipo_inversion_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['estado_proyecto_c'] = array(
    'name' => 'estado_proyecto_c',
    'vname' => 'LBL_ESTADO_PROYECTO',
    'type' => 'enum',
    'options' => 'estado_proyecto_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['django_submission_id_c'] = array(
    'name' => 'django_submission_id_c',
    'vname' => 'LBL_DJANGO_SUBMISSION_ID',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Opportunity']['fields']['webhook_event_id_c'] = array(
    'name' => 'webhook_event_id_c',
    'vname' => 'LBL_WEBHOOK_EVENT_ID',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);
PHP

write_lang_files "${EXT_BASE}/modules/Opportunities/Ext/Language" "sigi_cni_fields" "Opportunities field labels" <<'PHP'
$mod_strings['LBL_SECTOR'] = 'Sector';
$mod_strings['LBL_MONTO_INVERSION'] = 'Monto de inversión';
$mod_strings['LBL_EMPLEOS_ESTIMADOS'] = 'Empleos estimados';
$mod_strings['LBL_DEPARTAMENTO'] = 'Departamento';
$mod_strings['LBL_MUNICIPIO'] = 'Municipio';
$mod_strings['LBL_FECHA_ANUNCIO'] = 'Fecha de anuncio';
$mod_strings['LBL_FECHA_INICIO_ESTIMADA'] = 'Fecha inicio estimada';
$mod_strings['LBL_FECHA_FINALIZACION_ESTIMADA'] = 'Fecha finalización estimada';
$mod_strings['LBL_OBSTACULOS_IDENTIFICADOS'] = 'Obstáculos identificados';
$mod_strings['LBL_INSTITUCIONES_INVOLUCRADAS'] = 'Instituciones involucradas';
$mod_strings['LBL_PRIORIDAD'] = 'Prioridad';
$mod_strings['LBL_TIPO_INVERSION'] = 'Tipo de inversión';
$mod_strings['LBL_ESTADO_PROYECTO'] = 'Estado del proyecto';
$mod_strings['LBL_DJANGO_SUBMISSION_ID'] = 'ID postulación Django';
$mod_strings['LBL_WEBHOOK_EVENT_ID'] = 'ID evento webhook';
PHP

write_file "${EXT_BASE}/modules/Leads/Ext/Vardefs/sigi_cni_fields.php" <<'PHP'
<?php
// SIGI CNI — Leads custom fields (generated by apply-sigi-cni-suitecrm-customizations.sh)

$dictionary['Lead']['fields']['sector_interes_c'] = array(
    'name' => 'sector_interes_c',
    'vname' => 'LBL_SECTOR_INTERES',
    'type' => 'enum',
    'options' => 'sector_economico_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Lead']['fields']['fuente_entrada_c'] = array(
    'name' => 'fuente_entrada_c',
    'vname' => 'LBL_FUENTE_ENTRADA',
    'type' => 'enum',
    'options' => 'fuente_contacto_cni_list',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Lead']['fields']['pais_contacto_c'] = array(
    'name' => 'pais_contacto_c',
    'vname' => 'LBL_PAIS_CONTACTO',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Lead']['fields']['consentimiento_comunicaciones_c'] = array(
    'name' => 'consentimiento_comunicaciones_c',
    'vname' => 'LBL_CONSENTIMIENTO_COMUNICACIONES',
    'type' => 'bool',
    'default' => '0',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Lead']['fields']['django_submission_id_c'] = array(
    'name' => 'django_submission_id_c',
    'vname' => 'LBL_DJANGO_SUBMISSION_ID',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);

$dictionary['Lead']['fields']['webhook_event_id_c'] = array(
    'name' => 'webhook_event_id_c',
    'vname' => 'LBL_WEBHOOK_EVENT_ID',
    'type' => 'varchar',
    'len' => '120',
    'source' => 'custom_fields',
    'audited' => true,
    'required' => false,
);
PHP

write_lang_files "${EXT_BASE}/modules/Leads/Ext/Language" "sigi_cni_fields" "Leads field labels" <<'PHP'
$mod_strings['LBL_SECTOR_INTERES'] = 'Sector de interés';
$mod_strings['LBL_FUENTE_ENTRADA'] = 'Fuente de entrada';
$mod_strings['LBL_PAIS_CONTACTO'] = 'País del contacto';
$mod_strings['LBL_CONSENTIMIENTO_COMUNICACIONES'] = 'Consentimiento comunicaciones';
$mod_strings['LBL_DJANGO_SUBMISSION_ID'] = 'ID postulación Django';
$mod_strings['LBL_WEBHOOK_EVENT_ID'] = 'ID evento webhook';
PHP

echo ""
echo "Customizaciones SIGI CNI generadas (labels es_es + en_us)."
echo "Ahora ejecutar en SuiteCRM:"
echo "  Admin → Repair → Quick Repair and Rebuild"
echo "Luego ejecutar cualquier SQL sugerido por SuiteCRM para crear columnas *_cstm."
