#!/usr/bin/env bash
# Generate SIGI CNI EditView and DetailView layouts in custom/modules/*/metadata/.
# Does not modify core files or write to the database.
# Run from crm/: bash scripts/apply-sigi-cni-suitecrm-layouts.sh
#
# Prerequisites:
#   apply-sigi-cni-suitecrm-customizations.sh
#   register-sigi-cni-fields-metadata.sh (optional but recommended for Studio)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRM_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
LEGACY_DIR="${CRM_DIR}/suitecrm/public/legacy"
BACKUP_TS="$(date +%Y%m%d%H%M%S)"

if [[ ! -d "${LEGACY_DIR}" ]]; then
  echo "Error: SuiteCRM legacy path not found:"
  echo "  ${LEGACY_DIR}"
  echo ""
  echo "Install SuiteCRM locally under crm/suitecrm/ first."
  echo "Expected layout: crm/suitecrm/public/legacy/"
  exit 1
fi

CUSTOM_BASE="${LEGACY_DIR}/custom"
EXT_BASE="${CUSTOM_BASE}/Extension"
MODULES=(Accounts Contacts Opportunities Leads)

WRITE_TEST="${CUSTOM_BASE}/modules/.sigi_cni_write_test"
if ! mkdir -p "${WRITE_TEST}" 2>/dev/null; then
  echo "Error: cannot write under ${CUSTOM_BASE}/modules/"
  echo ""
  echo "SuiteCRM files may belong to the Docker web user (www-data)."
  echo "Fix ownership for local scripts, for example:"
  echo "  sudo chown -R \$(whoami):\$(whoami) suitecrm/public/legacy/custom"
  echo "Or run: bash scripts/fix-suitecrm-permissions.sh"
  exit 1
fi
rmdir "${WRITE_TEST}"

for module in "${MODULES[@]}"; do
  mkdir -p "${CUSTOM_BASE}/modules/${module}/metadata"
  mkdir -p "${EXT_BASE}/modules/${module}/Ext/Language"
done

write_with_backup() {
  local dest="$1"
  shift
  if [[ -f "${dest}" ]]; then
    cp "${dest}" "${dest}.bak.${BACKUP_TS}"
    echo "[BACKUP] ${dest#${CRM_DIR}/} -> $(basename "${dest}").bak.${BACKUP_TS}"
  fi
  cat > "${dest}"
  echo "[OK] ${dest#${CRM_DIR}/}"
}

write_lang_files_with_backup() {
  local dir="$1"
  local suffix="$2"
  local header="$3"
  shift 3
  local php_body
  php_body="$(cat)"
  local locale
  for locale in es_es en_us; do
    write_with_backup "${dir}/${locale}.${suffix}.php" <<PHP
<?php
// SIGI CNI — ${header} (${locale}; generated by apply-sigi-cni-suitecrm-layouts.sh)

${php_body}
PHP
  done
}

# --- Panel label extensions (merged on Quick Repair) ---

write_lang_files_with_backup "${EXT_BASE}/modules/Accounts/Ext/Language" "sigi_cni_layout" "layout panel labels" <<'PHP'
$mod_strings['LBL_SIGI_CNI_PANEL'] = 'SIGI CNI';
$mod_strings['LBL_SIGI_CNI_INVESTOR_PROFILE'] = 'Perfil del inversionista';
PHP

write_lang_files_with_backup "${EXT_BASE}/modules/Contacts/Ext/Language" "sigi_cni_layout" "layout panel labels" <<'PHP'
$mod_strings['LBL_SIGI_CNI_PANEL'] = 'SIGI CNI';
$mod_strings['LBL_SIGI_CNI_CONTACT_PROFILE'] = 'Perfil del contacto inversionista';
PHP

write_lang_files_with_backup "${EXT_BASE}/modules/Opportunities/Ext/Language" "sigi_cni_layout" "layout panel labels" <<'PHP'
$mod_strings['LBL_SIGI_CNI_PANEL'] = 'SIGI CNI';
$mod_strings['LBL_SIGI_CNI_PROJECT_PROFILE'] = 'Proyecto de inversión';
PHP

write_lang_files_with_backup "${EXT_BASE}/modules/Leads/Ext/Language" "sigi_cni_layout" "layout panel labels" <<'PHP'
$mod_strings['LBL_SIGI_CNI_PANEL'] = 'SIGI CNI';
$mod_strings['LBL_SIGI_CNI_LEAD_PROFILE'] = 'Datos del lead de inversión';
PHP

# --- Accounts ---

write_with_backup "${CUSTOM_BASE}/modules/Accounts/metadata/editviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Accounts EditView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Accounts']['EditView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'LBL_ACCOUNT_INFORMATION' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_INVESTOR_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'lbl_account_information' => array(
            array(
                array(
                    'name' => 'name',
                    'label' => 'LBL_NAME',
                    'displayParams' => array('required' => true),
                ),
                array('name' => 'website', 'type' => 'link', 'label' => 'LBL_WEBSITE'),
            ),
            array(
                array('name' => 'phone_office', 'label' => 'LBL_PHONE_OFFICE'),
                array('name' => 'email1', 'studio' => 'false', 'label' => 'LBL_EMAIL'),
            ),
            array(
                array('name' => 'assigned_user_name', 'label' => 'LBL_ASSIGNED_TO'),
            ),
            array(
                array('name' => 'description', 'label' => 'LBL_DESCRIPTION'),
            ),
        ),
        'lbl_sigi_cni_panel' => array(
            array(
                array('name' => 'estado_ciclo_vida_c', 'label' => 'LBL_ESTADO_CICLO_VIDA'),
                array('name' => 'cliente_objetivo_c', 'label' => 'LBL_CLIENTE_OBJETIVO'),
            ),
            array(
                array('name' => 'sector_economico_c', 'label' => 'LBL_SECTOR_ECONOMICO'),
                array('name' => 'pais_origen_c', 'label' => 'LBL_PAIS_ORIGEN'),
            ),
            array(
                array('name' => 'tipo_entidad_c', 'label' => 'LBL_TIPO_ENTIDAD'),
                array('name' => 'fuente_contacto_c', 'label' => 'LBL_FUENTE_CONTACTO'),
            ),
            array(
                array('name' => 'monto_potencial_c', 'label' => 'LBL_MONTO_POTENCIAL'),
                array('name' => 'empleos_potenciales_c', 'label' => 'LBL_EMPLEOS_POTENCIALES'),
            ),
            array(
                array('name' => 'fecha_primer_contacto_c', 'label' => 'LBL_FECHA_PRIMER_CONTACTO'),
                array('name' => 'ultima_interaccion_c', 'label' => 'LBL_ULTIMA_INTERACCION'),
            ),
        ),
    ),
);
PHP

write_with_backup "${CUSTOM_BASE}/modules/Accounts/metadata/detailviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Accounts DetailView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Accounts']['DetailView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'LBL_ACCOUNT_INFORMATION' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_INVESTOR_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'lbl_account_information' => array(
            array('name', 'website'),
            array('phone_office', 'email1'),
            array('assigned_user_name'),
            array('description'),
        ),
        'lbl_sigi_cni_panel' => array(
            array('estado_ciclo_vida_c', 'cliente_objetivo_c'),
            array('sector_economico_c', 'pais_origen_c'),
            array('tipo_entidad_c', 'fuente_contacto_c'),
            array('monto_potencial_c', 'empleos_potenciales_c'),
            array('fecha_primer_contacto_c', 'ultima_interaccion_c'),
        ),
    ),
);
PHP

# --- Contacts ---

write_with_backup "${CUSTOM_BASE}/modules/Contacts/metadata/editviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Contacts EditView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Contacts']['EditView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'default' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_CONTACT_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'default' => array(),
        'lbl_sigi_cni_panel' => array(
            array(
                array('name' => 'first_name', 'label' => 'LBL_FIRST_NAME'),
                array('name' => 'last_name', 'label' => 'LBL_LAST_NAME'),
            ),
            array(
                array('name' => 'title', 'label' => 'LBL_TITLE'),
                array('name' => 'account_name', 'label' => 'LBL_ACCOUNT_NAME'),
            ),
            array(
                array('name' => 'phone_work', 'label' => 'LBL_OFFICE_PHONE'),
                array('name' => 'phone_mobile', 'label' => 'LBL_MOBILE_PHONE'),
            ),
            array(
                array('name' => 'email1', 'studio' => 'false', 'label' => 'LBL_EMAIL_ADDRESS'),
            ),
            array(
                array('name' => 'pais_contacto_c', 'label' => 'LBL_PAIS_CONTACTO'),
                array('name' => 'cargo_institucional_c', 'label' => 'LBL_CARGO_INSTITUCIONAL'),
            ),
            array(
                array('name' => 'idioma_preferido_c', 'label' => 'LBL_IDIOMA_PREFERIDO'),
                array('name' => 'sector_interes_c', 'label' => 'LBL_SECTOR_INTERES'),
            ),
            array(
                array('name' => 'estado_lead_c', 'label' => 'LBL_ESTADO_LEAD'),
                array('name' => 'fuente_entrada_c', 'label' => 'LBL_FUENTE_ENTRADA'),
            ),
            array(
                array('name' => 'consentimiento_comunicaciones_c', 'label' => 'LBL_CONSENTIMIENTO_COMUNICACIONES'),
            ),
            array(
                array('name' => 'assigned_user_name', 'label' => 'LBL_ASSIGNED_TO'),
            ),
            array(
                array('name' => 'description', 'label' => 'LBL_DESCRIPTION'),
            ),
        ),
    ),
);
PHP

write_with_backup "${CUSTOM_BASE}/modules/Contacts/metadata/detailviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Contacts DetailView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Contacts']['DetailView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'default' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_CONTACT_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'default' => array(),
        'lbl_sigi_cni_panel' => array(
            array('first_name', 'last_name'),
            array('title', 'account_name'),
            array('phone_work', 'phone_mobile'),
            array('email1'),
            array('pais_contacto_c', 'cargo_institucional_c'),
            array('idioma_preferido_c', 'sector_interes_c'),
            array('estado_lead_c', 'fuente_entrada_c'),
            array('consentimiento_comunicaciones_c'),
            array('assigned_user_name'),
            array('description'),
        ),
    ),
);
PHP

# --- Opportunities ---

write_with_backup "${CUSTOM_BASE}/modules/Opportunities/metadata/editviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Opportunities EditView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Opportunities']['EditView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'default' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_PROJECT_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'default' => array(),
        'lbl_sigi_cni_panel' => array(
            array(
                array('name' => 'name'),
                array('name' => 'account_name', 'label' => 'LBL_ACCOUNT_NAME'),
            ),
            array(
                array('name' => 'sales_stage', 'label' => 'LBL_SALES_STAGE'),
                array('name' => 'amount', 'label' => 'LBL_AMOUNT'),
            ),
            array(
                array('name' => 'sector_c', 'label' => 'LBL_SECTOR'),
                array('name' => 'estado_proyecto_c', 'label' => 'LBL_ESTADO_PROYECTO'),
            ),
            array(
                array('name' => 'tipo_inversion_c', 'label' => 'LBL_TIPO_INVERSION'),
                array('name' => 'monto_inversion_c', 'label' => 'LBL_MONTO_INVERSION'),
            ),
            array(
                array('name' => 'empleos_estimados_c', 'label' => 'LBL_EMPLEOS_ESTIMADOS'),
                array('name' => 'departamento_c', 'label' => 'LBL_DEPARTAMENTO'),
            ),
            array(
                array('name' => 'municipio_c', 'label' => 'LBL_MUNICIPIO'),
                array('name' => 'prioridad_c', 'label' => 'LBL_PRIORIDAD'),
            ),
            array(
                array('name' => 'fecha_anuncio_c', 'label' => 'LBL_FECHA_ANUNCIO'),
                array('name' => 'fecha_inicio_estimada_c', 'label' => 'LBL_FECHA_INICIO_ESTIMADA'),
            ),
            array(
                array('name' => 'fecha_finalizacion_estimada_c', 'label' => 'LBL_FECHA_FINALIZACION_ESTIMADA'),
            ),
            array(
                array('name' => 'obstaculos_identificados_c', 'label' => 'LBL_OBSTACULOS_IDENTIFICADOS'),
            ),
            array(
                array('name' => 'instituciones_involucradas_c', 'label' => 'LBL_INSTITUCIONES_INVOLUCRADAS'),
            ),
            array(
                array('name' => 'django_submission_id_c', 'label' => 'LBL_DJANGO_SUBMISSION_ID'),
                array('name' => 'webhook_event_id_c', 'label' => 'LBL_WEBHOOK_EVENT_ID'),
            ),
            array(
                array('name' => 'assigned_user_name', 'label' => 'LBL_ASSIGNED_TO'),
            ),
            array(
                array('name' => 'description', 'label' => 'LBL_DESCRIPTION'),
            ),
        ),
    ),
);
PHP

write_with_backup "${CUSTOM_BASE}/modules/Opportunities/metadata/detailviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Opportunities DetailView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Opportunities']['DetailView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'default' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_PROJECT_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'default' => array(),
        'lbl_sigi_cni_panel' => array(
            array('name', 'account_name'),
            array('sales_stage', 'amount'),
            array('sector_c', 'estado_proyecto_c'),
            array('tipo_inversion_c', 'monto_inversion_c'),
            array('empleos_estimados_c', 'departamento_c'),
            array('municipio_c', 'prioridad_c'),
            array('fecha_anuncio_c', 'fecha_inicio_estimada_c'),
            array('fecha_finalizacion_estimada_c'),
            array('obstaculos_identificados_c'),
            array('instituciones_involucradas_c'),
            array('django_submission_id_c', 'webhook_event_id_c'),
            array('assigned_user_name'),
            array('description'),
        ),
    ),
);
PHP

# --- Leads ---

write_with_backup "${CUSTOM_BASE}/modules/Leads/metadata/editviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Leads EditView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Leads']['EditView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'default' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_LEAD_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'default' => array(),
        'lbl_sigi_cni_panel' => array(
            array(
                array('name' => 'first_name', 'label' => 'LBL_FIRST_NAME'),
                array('name' => 'last_name', 'label' => 'LBL_LAST_NAME'),
            ),
            array(
                array('name' => 'account_name', 'label' => 'LBL_ACCOUNT_NAME'),
                array('name' => 'title', 'label' => 'LBL_TITLE'),
            ),
            array(
                array('name' => 'phone_work', 'label' => 'LBL_OFFICE_PHONE'),
                array('name' => 'phone_mobile', 'label' => 'LBL_MOBILE_PHONE'),
            ),
            array(
                array('name' => 'email1', 'studio' => 'false', 'label' => 'LBL_EMAIL_ADDRESS'),
                array('name' => 'status', 'label' => 'LBL_STATUS'),
            ),
            array(
                array('name' => 'pais_contacto_c', 'label' => 'LBL_PAIS_CONTACTO'),
                array('name' => 'sector_interes_c', 'label' => 'LBL_SECTOR_INTERES'),
            ),
            array(
                array('name' => 'fuente_entrada_c', 'label' => 'LBL_FUENTE_ENTRADA'),
                array('name' => 'consentimiento_comunicaciones_c', 'label' => 'LBL_CONSENTIMIENTO_COMUNICACIONES'),
            ),
            array(
                array('name' => 'django_submission_id_c', 'label' => 'LBL_DJANGO_SUBMISSION_ID'),
                array('name' => 'webhook_event_id_c', 'label' => 'LBL_WEBHOOK_EVENT_ID'),
            ),
            array(
                array('name' => 'assigned_user_name', 'label' => 'LBL_ASSIGNED_TO'),
            ),
            array(
                array('name' => 'description', 'label' => 'LBL_DESCRIPTION'),
            ),
        ),
    ),
);
PHP

write_with_backup "${CUSTOM_BASE}/modules/Leads/metadata/detailviewdefs.php" <<'PHP'
<?php
// SIGI CNI — Leads DetailView layout (generated by apply-sigi-cni-suitecrm-layouts.sh)

$viewdefs['Leads']['DetailView'] = array(
    'templateMeta' => array(
        'maxColumns' => '2',
        'widths' => array(
            array('label' => '10', 'field' => '30'),
            array('label' => '10', 'field' => '30'),
        ),
        'useTabs' => false,
        'tabDefs' => array(
            'default' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
            'LBL_SIGI_CNI_LEAD_PROFILE' => array(
                'newTab' => false,
                'panelDefault' => 'expanded',
            ),
        ),
    ),
    'panels' => array(
        'default' => array(),
        'lbl_sigi_cni_panel' => array(
            array('first_name', 'last_name'),
            array('account_name', 'title'),
            array('phone_work', 'phone_mobile'),
            array('email1', 'status'),
            array('pais_contacto_c', 'sector_interes_c'),
            array('fuente_entrada_c', 'consentimiento_comunicaciones_c'),
            array('django_submission_id_c', 'webhook_event_id_c'),
            array('assigned_user_name'),
            array('description'),
        ),
    ),
);
PHP

echo ""
echo "Layouts SIGI CNI generados (labels es_es + en_us)."
echo "Ahora ejecutar:"
echo "  Admin → Repair → Quick Repair and Rebuild"
echo ""
echo "Luego limpiar caché del navegador si no se ven cambios."
