# Generated by Django 5.2.14 on 2026-06-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteCRMIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_model', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Modelo relacionado')),
                ('related_object_id', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='ID de objeto relacionado')),
                ('action', models.CharField(max_length=120, verbose_name='Acción')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload enviado')),
                ('response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Éxito')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de integración SuiteCRM',
                'verbose_name_plural': 'Logs de integración SuiteCRM',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=120, verbose_name='Origen')),
                ('event_type', models.CharField(db_index=True, max_length=150, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Procesado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
            ],
            options={
                'verbose_name': 'Evento de webhook',
                'verbose_name_plural': 'Eventos de webhook',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
