const shared = {
  ranges: ["under_10m", "10m_50m", "50m_100m", "over_100m"] as const,
};

export const postulacionPageCopy = {
  es: {
    metadata: { title: "Postula tu proyecto | CNI Honduras", description: "Presenta tu proyecto de inversión para recibir acompañamiento institucional del CNI." },
    hero: { eyebrow: "INVERSIÓN EN HONDURAS", title: "Postula tu proyecto", description: "Comparta su iniciativa con el CNI. Nuestro equipo revisará la información para orientar su ruta de inversión en Honduras." },
    intro: { title: "Información para evaluar su iniciativa", text: "Complete los campos requeridos. La información será tratada de forma confidencial y utilizada para dar seguimiento a su proyecto." },
    sections: { contact: "Contacto", company: "Empresa", project: "Proyecto", investment: "Inversión", location: "Ubicación", consent: "Consentimiento" },
    labels: { contact_name: "Nombre de contacto", email: "Correo electrónico", phone: "Teléfono", country: "País", company_name: "Nombre de la empresa", website: "Sitio web", project_name: "Nombre del proyecto", sector: "Sector", project_description: "Descripción del proyecto", investment_range: "Rango de inversión", estimated_jobs: "Empleos estimados", department: "Departamento", municipality: "Municipio", consent: "Autorizo al CNI a almacenar y procesar esta información y a contactarme para dar seguimiento al proyecto.", submit: "Enviar proyecto", submitAnother: "Enviar otro proyecto", portfolio: "Ver portafolio", home: "Ir al inicio", reference: "Código de referencia" },
    placeholders: { contact_name: "Nombre y apellido", email: "correo@empresa.com", phone: "+504 0000-0000", country: "País de origen", company_name: "Empresa u organización", website: "https://empresa.com", project_name: "Nombre de la iniciativa", project_description: "Describa el alcance, etapa actual y objetivos del proyecto.", estimated_jobs: "Ej. 120", select: "Seleccione una opción", selectDepartment: "Seleccione un departamento", selectMunicipality: "Seleccione un municipio" },
    rangeLabels: ["Menos de US$10 millones", "US$10 a US$50 millones", "US$50 a US$100 millones", "Más de US$100 millones"],
    required: "Obligatorio", optional: "Opcional", loadingDepartments: "Cargando departamentos...", loadingMunicipalities: "Cargando municipios...", geoError: "No se pudieron cargar las ubicaciones. Intente nuevamente.", municipalityError: "No se pudieron cargar los municipios.", sectorError: "No se pudieron cargar los sectores.", municipalityDisabled: "Seleccione primero un departamento", submitting: "Enviando...", serverError: "No pudimos recibir el proyecto. Revise los campos o intente nuevamente.", success: "Su proyecto fue recibido correctamente.", validation: { required: "Este campo es obligatorio.", email: "Ingrese un correo válido.", url: "Ingrese una URL válida.", description: "Ingrese al menos 20 caracteres.", jobs: "Ingrese un número entero mayor o igual a cero.", consent: "Debe aceptar el consentimiento." },
    benefits: { title: "Acompañamiento institucional", list: ["Orientación técnica para su proyecto", "Tratamiento confidencial de la información", "Seguimiento por el equipo del CNI"] },
    ...shared,
  },
  en: {
    metadata: { title: "Submit your project | CNI Honduras", description: "Submit your investment project for institutional support from CNI." },
    hero: { eyebrow: "INVESTING IN HONDURAS", title: "Submit your project", description: "Share your initiative with CNI. Our team will review the information to guide your investment path in Honduras." },
    intro: { title: "Information to assess your initiative", text: "Complete the required fields. Your information will be handled confidentially and used to follow up on your project." },
    sections: { contact: "Contact", company: "Company", project: "Project", investment: "Investment", location: "Location", consent: "Consent" },
    labels: { contact_name: "Contact name", email: "Email address", phone: "Phone", country: "Country", company_name: "Company name", website: "Website", project_name: "Project name", sector: "Sector", project_description: "Project description", investment_range: "Investment range", estimated_jobs: "Estimated jobs", department: "Department", municipality: "Municipality", consent: "I authorize CNI to store and process this information and contact me to follow up on the project.", submit: "Submit project", submitAnother: "Submit another project", portfolio: "View portfolio", home: "Go to home", reference: "Reference code" },
    placeholders: { contact_name: "First and last name", email: "email@company.com", phone: "+1 000 000 0000", country: "Country of origin", company_name: "Company or organization", website: "https://company.com", project_name: "Initiative name", project_description: "Describe the project's scope, current stage, and goals.", estimated_jobs: "E.g. 120", select: "Select an option", selectDepartment: "Select a department", selectMunicipality: "Select a municipality" },
    rangeLabels: ["Under US$10 million", "US$10 to US$50 million", "US$50 to US$100 million", "Over US$100 million"],
    required: "Required", optional: "Optional", loadingDepartments: "Loading departments...", loadingMunicipalities: "Loading municipalities...", geoError: "Locations could not be loaded. Please try again.", municipalityError: "Municipalities could not be loaded.", sectorError: "Sectors could not be loaded.", municipalityDisabled: "Select a department first", submitting: "Submitting...", serverError: "We could not receive your project. Review the fields or try again.", success: "Your project was submitted successfully.", validation: { required: "This field is required.", email: "Enter a valid email address.", url: "Enter a valid URL.", description: "Enter at least 20 characters.", jobs: "Enter a whole number greater than or equal to zero.", consent: "You must accept the consent." },
    benefits: { title: "Institutional support", list: ["Technical guidance for your project", "Confidential handling of information", "Follow-up by the CNI team"] },
    ...shared,
  },
} as const;
