# Generated by Django 5.2.14 on 2026-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_cniregion_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(max_length=140),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='unique_municipality_slug_per_department'),
        ),
    ]
