# Generated by Django 5.2.16 on 2026-09-02 15:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_municipality_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('infrastructure_type', models.CharField(choices=[('port', 'Puerto'), ('airport', 'Aeropuerto')], max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(blank=True, default='')),
                ('operator', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, default='', max_length=120)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_infrastructure', to='geo.department')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_infrastructure', to='geo.municipality')),
            ],
            options={
                'verbose_name': 'Infraestructura estratégica',
                'verbose_name_plural': 'Infraestructura estratégica',
                'ordering': ('name',),
            },
        ),
    ]
