# Generated by Django 5.2.16 on 2026-10-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_strategicinfrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cniregion',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cniregion',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cniregion',
            name='level',
            field=models.CharField(choices=[('macro', 'Macroregión'), ('sub', 'Subregión'), ('polo', 'Polo de desarrollo')], db_index=True, default='sub', max_length=10),
        ),
        migrations.AddField(
            model_name='cniregion',
            name='municipalities',
            field=models.ManyToManyField(blank=True, related_name='cni_regions', to='geo.municipality'),
        ),
        migrations.AddField(
            model_name='cniregion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.cniregion'),
        ),
    ]
