# Generated by Django 5.2.16 on 2026-10-01 21:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_cniregion_territorial_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadCorridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('ref', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('name_es', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('road_class', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=12)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('length_km', models.PositiveIntegerField(default=0)),
                ('is_strategic', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='', null=True)),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('source_name', models.CharField(max_length=120)),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Corredor vial',
                'verbose_name_plural': 'Corredores viales',
                'ordering': ('ref', 'code'),
            },
        ),
    ]
